version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: fincheck-app
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
