version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fincheck-app
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"

